sonicecommerce/cadmin/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.admin_login,name='admin_login'),
    path('dasbord/',views.admin_dashbord,name='admin_dashbord'),
    path('userview/',views.user_detail,name='user_detail_page'),
    path('product_detail/',views.product_details,name='product_detail_page'),
    path('block_user/<int:user_id>/', views.block_user, name='block_user'),
    path('unblock_user/<int:user_id>/', views.unblock_user, name='unblock_user'),
   
    path('edit-product/<int:product_id>/',views.edit_product, name='edit_product'),
    path('delete-product-image/<int:image_id>/',views.delete_product_image, name='delete_product_image'),
    path('add-product/',views.add_product, name='add_product'),
    path('category-detail/',views.category_detail,name='category_datail_page'),
    path('desable-product/<int:product_id>/',views.disable_product,name="disable_product"),
    path('enable-product/<int:product_id>/',views.enable_product,name="enable_product"),
    path('add-category/',views.add_category,name="add_category"),
    path('edit-category/<int:category_id>/',views.edit_category,name="edit_category"),
    path('desable-category/<int:category_id>/',views.desable_category,name="desable_category"),
    path('enable-category/<int:category_id>/',views.enable_category,name="enable_category"),
    path('coupon-detail/',views.coupon_detail,name="coupon_detail"),
    
    path('add_coupon/', views.add_coupon, name='add_coupon'),
    path('admin/order-requests/', views.manage_order_requests, name='manage_order_requests'),
    path('delete_coupon/<int:id>/', views.delete_coupon, name='delete_coupon'),
    

    # Order Management URLs
    path('order-list/', views.order_list, name='order_list'),
    #path('order/<int:order_id>/', views.order_detail, name='order_detail'),
    path('order/<int:order_id>/update-status/', views.update_order_status, name='update_order_status'),
    path('admin/order-request/<int:request_id>/<str:action>/<int:user>/',views.approve_or_reject_request, name='approve_or_reject_request'),
    path('order/<int:order_id>/cancel/', views.cancel_order, name='cancel_order'),


    path('change-status/<int:order_id>/<str:status>/',views.change_order_status, name='change_order_status'),
    path('sale_report/',views.sale_report, name='sale_report'),
    path('download_excel/',views.download_excel, name='download_excel'),
    path('download_pdf/',views.download_pdf, name='download_pdf'),

    path('logoutt/',views.logout,name="logoutt"),

    path('get_sales_data/<str:period>/', views.get_sales_data, name='get_sales_data'),
    path('cadmin_order_details/<int:order_id>/',views.cadmin_order_details,name='cadmin_order_details'),
]

sonicecommerce/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='homepage')
]

sonicecommerce/sonicecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('store/', include('store.urls')),
    path('accounts/', include('accounts.urls')),  # Your custom URLs
    path('accounts/', include('allauth.urls')),  # Allauth URLs
    path('cadmin/', include('cadmin.urls')),
    path('cart/', include('carts.urls')),

    path('orders/',include('orders.urls')),
    path('coupon/',include('coupon.urls')),
    path('wishlist/',include('wishlist.urls')),
    path('wallet/',include('wallet.urls')),
    path('offers/',include('offers.urls')),
    path('variations/',include('variation.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sonicecommerce/variation/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('',views.variation_view,name="variation_view"),
   path('variations/add/', views.variation_create, name='variation_create'),
   path('variations/<int:pk>/edit/', views.variation_update, name='variation_update'),
    path('variations/<int:pk>/toggle/', views.variation_toggle_status, name='variation_toggle_status'),
]

sonicecommerce/variation/models.py
from django.db import models
from store.models import Product

# Choices for variation category
VARIATION_CATEGORY_CHOICES = (
    ('color', 'Color'),
    ('size', 'Size'),
)

class VariationManager(models.Manager):
    def colors(self):
        """Return all variations that are of category 'color' and are active."""
        return self.filter(variation_category='color', is_active=True)

    def sizes(self):
        """Return all variations that are of category 'size' and are active."""
        return self.filter(variation_category='size', is_active=True)

class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=VARIATION_CATEGORY_CHOICES, db_index=True)
    variation_value = models.CharField(max_length=100)
    quantity = models.PositiveIntegerField(default=0)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    defult=models.BooleanField(default=False,db_index=True)
    is_active = models.BooleanField(default=True, db_index=True)
    created_date = models.DateField(auto_now=True)

    objects = VariationManager()

    def clean(self):
        """Ensure that price and quantity are not negative."""
        if self.price < 0:
            raise ValidationError('Price cannot be negative.')
        if self.quantity < 0:
            raise ValidationError('Quantity cannot be negative.')

    def __str__(self):
        """Return a string representation of the variation."""
        return f"{self.variation_category.capitalize()}: {self.variation_value} - ${self.price:.2f} ({self.quantity} in stock)"

    class Meta:
        """Meta options for the Variation model."""
        verbose_name = "Variation"
        verbose_name_plural = "Variations"

sonicecommerce/cadmin/views.py
from django.shortcuts import render,redirect
from accounts.models import Accounts 
from category.models import Category
from category.forms import CategoryForm
from django.urls import reverse_lazy 
from store.models import Product,ProductImage
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from accounts.forms import UserEditForm
from django.contrib import messages, auth
from coupon.models import Coupon
from coupon.forms import CouponForm
from store.forms import ProductForm,ProductImageFormSet
import json
from store.pipeline import get_best_offer,calculate_discounted_price
from orders.models import Order,OrderProduct,Payment,OrderRequest
from django.forms import modelformset_factory
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.db.models import Q
from datetime import datetime, timedelta 
import openpyxl
from django.http import HttpResponse
from django.utils.dateparse import parse_date
from django.utils.timezone import now
from django.core.paginator import Paginator
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from io import BytesIO
from django.contrib.auth.decorators import user_passes_test
# Create your views here.
from django.core.files.base import ContentFile
from django.db.models import Sum, F, ExpressionWrapper, FloatField
from django.db.models.functions import Cast
from wallet.models import Wallet,WalletTransaction
from decimal import Decimal
from django.utils import timezone

def admin_login(request):
    if request.user.is_authenticated and request.user.is_admin:
        
        return redirect('admin_dashbord')

    if request.method=="POST":
        email = request.POST['email']
        password = request.POST['password']

        user = auth.authenticate(request, email=email, password=password)

        if user is not None and user.is_admin:
            auth.login(request, user)
            return redirect('admin_dashbord')
        else:
            messages.error(request, 'Invalid login credentials')
            return redirect('admin_login')   

    return render(request,'cadmin/adminlogin.html')
@user_passes_test(lambda u: u.is_superadmin, login_url="admin_login")
def admin_dashbord(request):
    product_count = Product.objects.filter(is_available=True).count()
    order_count = Order.objects.filter(is_orderd=True).count()

    new_order = Order.objects.filter(status='New').count()
    cancelled_order = Order.objects.filter(status='Cancelled').count()
    delivered_order = Order.objects.filter(status='Deliverd').count()
    shipped_order = Order.objects.filter(status='Shipped').count()

    # Best-selling products based on quantity sold
    best_selling_products = (OrderProduct.objects
                             .values('product__product_name')
                             .annotate(total_quantity_sold=Sum('quantity'))
                             .order_by('-total_quantity_sold')[:10])

    best_selling_category = (OrderProduct.objects
                             .values('product__category__category_name')
                             .annotate(total_category_sales=Sum('quantity'))
                             .order_by('-total_category_sales').first())

    if best_selling_category:
        top_selling_category_name = best_selling_category['product__category__category_name']
        top_selling_category_count = best_selling_category['total_category_sales']
    else:
        top_selling_category_name = "No sales yet"
        top_selling_category_count = 0

    context = {
        'product_count': product_count,
        'order_count': order_count,
        'new_order': new_order,
        'cancelled_order': cancelled_order,
        'delivered_order': delivered_order,
        'shipped_order': shipped_order,
        'best_selling_products': best_selling_products,
        'top_selling_category_name': top_selling_category_name,
        'top_selling_category_count': top_selling_category_count
    }

    return render(request, 'cadmin/dashbord.html', context)

# View to provide sales data as JSON
@user_passes_test(lambda u: u.is_superadmin, login_url="admin_login")
def get_sales_data(request, period='month'):
    if period == 'year':
        current_year = datetime.now().year
        labels = [str(year) for year in range(current_year - 5, current_year + 1)]  # Last 5 years
        data = []
        
        # Loop through each year and calculate the total sales for that year
        for year in range(current_year - 5, current_year + 1):
            total_sales = Order.objects.filter(
                is_orderd=True, 
                created_at__year=year
            ).aggregate(total_sales=Sum('order_total'))['total_sales'] or 0
            data.append(total_sales)
    else:
        current_year = datetime.now().year
        labels = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        data = []
        
        # Loop through each month of the current year and calculate the total sales for that month
        for month in range(1, 13):
            total_sales = Order.objects.filter(
                is_orderd=True, 
                created_at__year=current_year, 
                created_at__month=month
            ).aggregate(total_sales=Sum('order_total'))['total_sales'] or 0
            data.append(total_sales)
    
    response = {
        'labels': labels,
        'data': data
    }

    return JsonResponse(response)

@user_passes_test(lambda u:u.is_superadmin,login_url="admin_login")
def user_detail(request):
    users_list = Accounts.objects.all().order_by('date_joined')
    
    # Pagination: 10 users per page
    paginator = Paginator(users_list, 10)  
    page_number = request.GET.get('page')
    users = paginator.get_page(page_number)
    
    context = {
        'users': users
    }
    return render(request, 'cadmin/users.html', context)
@user_passes_test(lambda u:u.is_superadmin,login_url="admin_login")
def block_user(request,user_id):
    try:
        user = Accounts.objects.get(id=user_id)
        user.is_active = False
        user.save()
    except Accounts.DoesNotExist:
         messages.error(request, 'User not found.')
    return redirect('user_detail_page')

@user_passes_test(lambda u:u.is_superadmin,login_url="admin_login")
def unblock_user(request, user_id):
    try:
        user = Accounts.objects.get(id=user_id)
        user.is_active = True
        user.save()
    except Accounts.DoesNotExist:
        messages.error(request, 'User not found.')
    return redirect('user_detail_page')

@user_passes_test(lambda u:u.is_superadmin,login_url="admin_login")
def product_details(request):
    products = Product.objects.all()
    paginator = Paginator(products, 10)  # 1 product per page
    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)
    
    context = {
        'products': products
    }
    return render(request, 'cadmin/product_details.html', context)

@user_passes_test(lambda u:u.is_superadmin,login_url="admin_login")
def add_product(request):
    if request.method == 'POST':
        product_form = ProductForm(request.POST, request.FILES)
        formset = ProductImageFormSet(request.POST, request.FILES, prefix='images')

        if product_form.is_valid() and formset.is_valid():
            product = product_form.save(commit=False)
            product.save()

            # Save the images from the formset
            for form in formset.cleaned_data:
                if form:
                    image = form['image']  # Access the image field from the cleaned data
                    ProductImage.objects.create(product=product, image=image)

            return JsonResponse({'success': True, 'message': 'Product added successfully'})
        else:
            errors = {
                'product_errors': product_form.errors.as_json(),
                'formset_errors': json.dumps(formset.errors)
            }
            return JsonResponse({'success': False, 'message': 'Form validation failed', 'errors': errors})
            

    else:
        product_form = ProductForm()
        formset = ProductImageFormSet(prefix='images')
        return render(request, 'cadmin/add_product.html', {
            'product_form': product_form,
            'formset': formset,
        })
    return redirect('product_detail_page')    

@user_passes_test(lambda u:u.is_superadmin,login_url="admin_login")
def edit_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        formset = ProductImageFormSet(request.POST, request.FILES, instance=product)
        
        if form.is_valid() and formset.is_valid():
            #if form.is_valid() and formset.is_valid():
            form.save()
            formset.save()
            return redirect(reverse_lazy('product_detail_page'))  # Redirect to the admin panel or another page
        else:
            messages.error(request, 'Please correct product details or image uploads.')
            #print(form.errors) 
            #print(formset.error)
    else:
        form = ProductForm(instance=product)
        formset = ProductImageFormSet(instance=product)
    
    return render(request, 'cadmin/edit_product.html', {'form': form, 'formset': formset, 'product': product})

@user_passes_test(lambda u:u.is_superadmin,login_url="admin_login")
def delete_product_image(request, image_id):
    image = get_object_or_404(ProductImage, id=image_id)
    image.delete()
    return redirect(request.META.get('HTTP_REFERER', 'product_detail_page'))    

@user_passes_test(lambda u:u.is_superadmin,login_url="admin_login")
def disable_product(request,product_id):
    product=get_object_or_404(Product, id=product_id)
    product.is_available=False

sonicecommerce/variation/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Variation
from django.contrib import messages
from .forms import VariationForm
from django.core.paginator import Paginator
# Create your views here.
def variation_view(request):
    variations = Variation.objects.all()
    paginator = Paginator(variations, 10)  # Show 10 variations per page
    page_number = request.GET.get('page')
    variations = paginator.get_page(page_number)
    
    context = {
        'variations': variations
    }
    return render(request, 'cadmin/variation.html', context)


def variation_create(request):
    if request.method == 'POST':
        form = VariationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Variation added successfully.')
            return redirect('variation_view')  # Redirect to a view that lists all variations
    else:
        form = VariationForm()
    return render(request, 'cadmin/variation_form.html', {'form': form})

def variation_update(request, pk):
    variation = get_object_or_404(Variation, pk=pk)
    if request.method == 'POST':
        form = VariationForm(request.POST, instance=variation)
        if form.is_valid():
            form.save()
            messages.success(request, 'Variation updated successfully.')
            return redirect('variation_view')
    else:
        form = VariationForm(instance=variation)
    return render(request, 'cadmin/variation_form.html', {'form': form})    
    
def variation_toggle_status(request, pk):
    variation = get_object_or_404(Variation, pk=pk)
    variation.is_active = not variation.is_active
    variation.save()
    status = "enabled" if variation.is_active else "disabled"
    messages.success(request, f'Variation {status} successfully.')
    return redirect('variation_view')

sonicecommerce/templates/cadmin/add_category.html
{% extends 'cadmin/base.html' %}

{% block content %}
<body>
    
    <div class="container">
        <h1>Add Category</h1>
       
        <form  method="POST"enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-12">
                    <label>Category Name</label> 
                    {{ form.category_name }}
                </div>
                <div class="form-group col-md-12">
                    <label>Category Slug</label> 
                    {{  form.slug }}
                </div>
                <div class="form-group col-md-12">
                    <label>Descriotion</label> 
                    {{  form.description }}
                </div>
                <div class="form-group col-md-6">
                    <label>Category Image</label> 
                    {{ form.cat_image }}
                </div>
                <div class="form-group col-md-6">
                    <label>Is Active</label> 
                    {{ form.is_active }}
                </div>
               
            </div>
            <div class="form-group">
                <button type="submit" class="btn-submit">Submit</button>
                <button type="reset" class="btn-cancel">Cancel</button>
            </div>
        </form>
        
    </div>
</body>

{% endblock %}

sonicecommerce/templates/cadmin/add_coupon.html
{% extends 'cadmin/base.html' %}
{% block content %}
<h2>Add Coupon</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
<a href="{% url 'coupon_detail' %}">Back to Coupons</a>


{% endblock %}

sonicecommerce/templates/cadmin/add_offer.html
{% extends "cadmin/base.html" %}

{% block content %}
  <h2>Add New Offer</h2>
  {% include "includes/alerts.html" %}
  <form method="post">
    {% csrf_token %}
    
    <div class="form-group">
      <label for="id_offer_type">Offer Type</label>
      {{ form.offer_type }}
    </div>
    
    <div class="form-group">
      <label for="id_category">Category</label>
      {{ form.category }}
    </div>
    
    <div class="form-group">
      <label for="id_product">Product</label>
      {{ form.product }}
    </div>

    <div class="form-group">
      <label for="id_percentage">Percentage</label>
      {{ form.percentage }}
    </div>
    
    <div class="form-group">
      <label for="id_valid_from">Valid From</label>
      {{ form.valid_from }}
    </div>
    
    <div class="form-group">
      <label for="id_valid_to">Valid To</label>
      {{ form.valid_to }}
    </div>
    
    <div class="form-group">
      <label for="id_is_active">Active</label>
      {{ form.is_active }}
    </div>

    <button type="submit" class="btn btn-primary">Save Offer</button>
    <a href="{% url 'offer_view' %}" class="btn btn-secondary">Cancel</a>
  </form>

  {% block extra_js %}
  <script>
  document.addEventListener('DOMContentLoaded', function() {
      const offerTypeSelect = document.getElementById('id_offer_type');
      const productField = document.getElementById('id_product');
      const categoryField = document.getElementById('id_category');

      function updateFields() {
          if (offerTypeSelect.value === 'category') {
              productField.disabled = true;
              productField.value = '';  // Clear the product field when disabled
              categoryField.disabled = false; // Ensure category field is enabled
          } else if (offerTypeSelect.value === 'product') {
              productField.disabled = false;
              categoryField.disabled = true;
              categoryField.value = ''; // Clear the category field when disabled
          } else {
              // Enable both fields if offer_type is neither 'category' nor 'product'
              productField.disabled = false;
              categoryField.disabled = false;
          }
      }

      // Initialize on page load
      updateFields();
      
      // Update on change
      offerTypeSelect.addEventListener('change', updateFields);
  });
  </script>
  {% endblock %}
{% endblock %}

sonicecommerce/templates/cadmin/cancel_order.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">Cancel Order - {{ order.order_number }}</h2>
    <p>Are you sure you want to cancel this order?</p>
    <form method="post" action="{% url 'cancel_order' order.id %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, Cancel Order</button>
        <a href="{% url 'order_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

sonicecommerce/templates/cadmin/categorydetail.html
{% extends 'cadmin/base.html' %}

{% block content %}
<body>
   
     
        <main>
           
                <h2>Categories</h2>
                <div class="search-bar">
                    <form method="GET" action="">
                        <input type="text" name="query" placeholder="Search" class="search-input" value="{{ request.GET.query }}">
                        <button type="submit" class="search-button">Search</button>
                    </form>
                </div>
                <table>
                    <thead>
                        <tr>
                            <th data-label="category ID">Category ID</th>
                            <th data-label="Name">Name</th>
                            <th data-label="slug">Slug</th>
                            <th data-label="Description">Description</th>
                            <th data-label="Image">Image</th>
                            <th data-label="Options">Options</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for category in categories %}
                        <tr>
                            <td data-label="Category ID">{{ category.id }}</td>
                            <td data-label="Name">{{ category.category_name }}</td>
                            <td data-label="Slug">{{ category.slug }}</td>
                            <td data-label="Description">{{ category.description }}</td>
                            <td data-label="Image">
                                {% if category.cat_image %}
                                    <img src="{{ category.cat_image.url }}" alt="{{ category.category_name }}" class="product-image">
                                {% else %}
                                    No Image
                                {% endif %}
                            </td>
                           
                                <td data-label="Options">
                              
                                    {% if category.is_active %}
                                    <a href="{% url 'desable_category' category.id %}">Disable</a>
                                    <a href="{% url 'edit_category' category.id %}">Edit</a>
                                    {% else %}
                                    <a href="{% url 'enable_category' category.id %}" >Enable</a>
                                    {% endif %}
                                  
                                </td>
                            
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="pagination">
                    <span class="step-links">
                        {% if categories.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ categories.previous_page_number }}">previous</a>
                        {% endif %}
            
                        <span class="current">
                            Page {{ categories.number }} of {{ categories.paginator.num_pages }}.
                        </span>
            
                        {% if categories.has_next %}
                            <a href="?page={{ categories.next_page_number }}">next</a>
                            <a href="?page={{ categories.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
                <a href="{% url 'add_category' %}" class="add-product-btn">Add Category</a>
         
        </main>
   
</body>

{% endblock %}

sonicecommerce/templates/cadmin/edit_category.html
{% extends 'cadmin/base.html' %}

{% block content %}
<body>
    <div class="container ">
        <h1>Edit Category</h1>
        
        <form  method="POST"enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-12">
                    <label>Category Name</label> 
                    {{ form.category_name }}
                </div>
                <div class="form-group col-md-12">
                    <label>Category Slug</label> 
                    {{  form.slug }}
                </div>
                <div class="form-group col-md-12">
                    <label>Descriotion</label> 
                    {{  form.description }}
                </div>
                <div class="form-group col-md-6">
                    <label>Category Image</label> 
                    {{ form.cat_image }}
                </div>
                <div class="form-group col-md-6">
                    <label>Is Active</label> 
                    {{ form.is_active }}
                </div>
               
            </div>
            <div class="form-group">
                <button type="submit" class="btn-submit">Submit</button>
                <button type="reset" class="btn-cancel">Cancel</button>
            </div>
        </form>
    </div>
   
</body>

{% endblock  %}

sonicecommerce/templates/cadmin/edit_offer.html
{% extends "cadmin/base.html" %}

{% block content %}
  <h2>Edit Offer</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Update Offer</button>
    <a href="{% url 'offer_view' %}" class="btn btn-secondary">Cancel</a>  <!-- Replace with the actual URL name -->
  </form>
{% endblock %}

sonicecommerce/templates/cadmin/offer_list.html
{% extends 'cadmin/base.html' %}
{% block content %}
<body>
   
     
    <main>
       
            <h2>Categories</h2>
            <div class="search-bar">
                <form method="GET" action="">
                    <input type="text" name="query" placeholder="Search" class="search-input" value="{{ request.GET.query }}">
                    <button type="submit" class="search-button">Search</button>
                </form>
            </div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Offer Type</th>
                        <th>Category</th>
                        <th>Product</th>
                        <th>Discount percentage</th>
                        <th>Valid From</th>
                        <th>Valid To</th>
                        <th>Is Active</th>
                        <th>Option</th>
                        
                    </tr>
                </thead>
                <tbody>
                    {% for offer in offers %}
                    <tr>
                        <td>{{ offer.offer_type }}</td>
                        <td>{{ offer.category }}</td>
                        <td>+{{ offer.product }}</td>
                        <td>{{ offer.percentage }}</td>
                        <td>{{ offer.valid_from }}</td>
                        <td>{{ offer.valid_to }}</td>
                        <td>{{ offer.is_active }}</td>
                       
                        <td>
                            <div class="button-container">
                                <a href="{% url 'edit_offer' offer_id=offer.id %}" >Edit</a>
                                {% if offer.is_active %}
                                <a href="{% url 'toggle_offer_status' offer.id %}" class="#">Deactivate</a>
                               {% else %}
                                <a href="{% url 'toggle_offer_status' offer.id %}" class="#">Activate</a>
                               {% endif %}
                            </div>
                            
                            
                          
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="pagination">
                <span class="step-links">
                    {% if offers.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ offers.previous_page_number }}">previous</a>
                    {% endif %}
        
                    <span class="current">
                        Page {{ offers.number }} of {{ offers.paginator.num_pages }}.
                    </span>
        
                    {% if offers.has_next %}
                        <a href="?page={{ offers.next_page_number }}">next</a>
                        <a href="?page={{ offers.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
            <a href="{% url 'add_offer' %}" class="add-product-btn">Add Offer</a>
     
    </main>

</body>
{% endblock %}